include $(CLEAR_VARS)
LOCAL_STATIC_LIBRARES := libgui_vendor
LOCAL_MODULE := libfui
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_VENDOR_MODULE := true
include $(BUILD_SHARED_LIBRARY)